import Link from 'next/link';
import {notFound} from 'next/navigation';
import {isLocale} from '@/lib/catalogue';
import {copy} from '@/content/copy';
import {loadCatalogue} from '@/lib/load-catalogue';
import {HeroInstrument} from '@/components/hero-instrument';
import {ProductCard} from '@/components/product-card';
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const {locale}=await params;return {title:locale==='ar'?'أجهزة القياس الصناعية | الأمل':'Industrial instrumentation | EL AMAL',description:locale==='ar'?'تصفح أدوات قياس الضغط والحرارة والملحقات.':'Explore pressure and temperature instruments and accessories.'};}
export default async function Home({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;if(!isLocale(locale))notFound();const t=copy[locale],ar=locale==='ar';const {products,categories,source}=await loadCatalogue();
 return <><section className="hero"><div className="hero-copy"><p className="hero-intro"><span/>{ar?'أجهزة القياس الصناعية':'Industrial measurement, considered.'}</p><h1>{ar?<>الدقة.<br/>في كل<br/>تفصيلة.</>:<>Precision.<br/>At every<br/>connection.</>}</h1><p className="hero-description">{ar?'أدوات الضغط والحرارة والملحقات. ابحث عن الطراز، وحدد متطلباتك، واطلب عرض سعر من الأمل.':'Pressure, temperature and the connections between. Find your instrument and bring your requirements to EL AMAL.'}</p><form className="hero-search" action={`/${locale}/products`}><label className="sr-only" htmlFor="hero-query">{t.search}</label><span aria-hidden="true">⌕</span><input id="hero-query" name="q" maxLength={120} placeholder={t.search}/><button aria-label={t.searchButton}><span aria-hidden="true">↗</span></button></form><Link className="hero-link" href={`/${locale}/products`}>{t.browse}<span aria-hidden="true">↗</span></Link></div><HeroInstrument locale={locale}/><div className="hero-bottom"><span>{ar?'الضغط / الحرارة / الملحقات':'Pressure / Temperature / Accessories'}</span><a href="#catalogue">{ar?'اكتشف المزيد':'Explore below'} <span aria-hidden="true">↓</span></a></div></section>
 <section id="catalogue" className="section catalogue-intro"><div className="section-heading"><div><p className="section-kicker">{ar?'الأدوات المناسبة لمتطلباتك':'Built around your requirements'}</p><h2>{ar?'ابدأ بما تحتاج\nإلى قياسه.':'Start with what\nyou need to measure.'}</h2></div><p>{ar?'من الطراز إلى التكوين، طريق واضح للوصول إلى الأداة المناسبة.':'From model to configuration, a clearer path to the instrument you need.'}</p></div><div className="category-list">{categories.map((c,i)=><Link key={c.id} href={`/${locale}/categories/${c.id}`} className="category-row"><span className={`category-icon category-icon-${c.id}`} aria-hidden="true">{['◉','♧','⊞'][i%3]}</span><h3>{c.name[locale]}</h3><p>{c.description[locale]}</p><span className="category-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="section selected-section"><div className="section-heading"><div><p className="section-kicker">{ar?'نظرة أقرب':'A closer look'}</p><h2>{ar?'أدوات القياس،\nبكل تفاصيلها.':'Instruments,\nin detail.'}</h2></div><Link className="text-link" href={`/${locale}/products`}>{t.all}<span aria-hidden="true">↗</span></Link></div><div className="featured-grid">{products.slice(0,3).map(p=><ProductCard key={p.id} product={p} locale={locale} demo={source==='demo'}/>)}</div></section>
 <section id="approach" className="approach section"><div><p className="section-kicker">{ar?'من المتطلبات إلى عرض السعر':'From requirement to quotation'}</p><h2>{ar?'التفاصيل أولاً.\nثم القرار.':'The details first.\nThe decision next.'}</h2><p className="approach-description">{ar?'الطراز ليس سوى البداية. يتيح طلب عرض السعر تأكيد التكوين والتوفر والتفاصيل التجارية قبل اتخاذ القرار.':'The model is only the beginning. A quotation enquiry brings configuration, availability and commercial details into the same conversation.'}</p></div><ol className="process-list">{(ar?[['حدد أداتك','ابحث بالطراز أو تصفح حسب فئة القياس.'],['اجمع متطلباتك','أضف الأدوات والكميات إلى سلة عرض السعر.'],['أكد التفاصيل','تُراجع الملاءمة الفنية والتوفر والسعر قبل الاتفاق.']]:[['Find your instrument','Search by model or explore a measurement category.'],['Build your requirement','Collect instruments and quantities in your quote basket.'],['Confirm the details','Technical suitability, availability and pricing need confirmation.']]).map(([title,desc],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></li>)}</ol></section>
 <section className="section industries" id="industries"><div className="section-heading"><div><p className="section-kicker">{ar?'سياق كل عملية':'The context behind every process'}</p><h2>{ar?'تختلف القطاعات.\nوتبقى أهمية الدقة.':'Different industries.\nThe same attention to detail.'}</h2></div></div><div className="industry-list">{(ar?['النفط والغاز','الصناعات الدوائية','الأغذية والمشروبات','الإنشاءات والمقاولات الهندسية']:['Oil & gas','Pharmaceutical','Food & beverage','Construction & EPC']).map(name=><div key={name}><span className="industry-dot"/><h3>{name}</h3></div>)}</div><p className="industry-note">{ar?'يجب تأكيد ملاءمة الأداة لكل تطبيق بواسطة المراجع الفني.':'Instrument suitability for each application requires technical confirmation.'}</p></section><section className="closing"><p>{ar?'هل تعرف ما تبحث عنه؟':'Know what you’re looking for?'}</p><h2>{ar?'ابدأ بالطراز.':'Start with the model.'}</h2><Link className="button button-light" href={`/${locale}/products`}>{t.browse}<span aria-hidden="true">↗</span></Link></section></>;
}
