import {pageMetadata} from '@/lib/page-metadata';
import {WikaEvidence} from '@/components/wika-evidence';
import {industries} from '@/content/industries';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {isLocale} from '@/lib/catalogue';
import {copy} from '@/content/copy';
import {loadCatalogue} from '@/lib/load-catalogue';
import {PrecisionHero} from '@/components/precision-hero';
import {ProductCard} from '@/components/product-card';
import {MeasurementIcon} from '@/components/measurement-icon';
import {RevealText} from '@/components/reveal-text';
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();return pageMetadata(locale,'',locale==='ar'?'أجهزة القياس الصناعية':'Industrial instrumentation',locale==='ar'?'تصفح أدوات قياس الضغط والحرارة والملحقات وابدأ طلب عرض سعر.':'Explore pressure and temperature instruments and accessories, and prepare a quotation request.');}
export default async function Home({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;if(!isLocale(locale))notFound();const t=copy[locale],ar=locale==='ar';const {products,categories,source}=await loadCatalogue();
 const featured=source==='cms'?categories.flatMap(c=>products.filter(p=>p.category===c.id).slice(0,1)).slice(0,3):products.slice(0,3);
 return <><PrecisionHero locale={locale}/>
 <section id="catalogue" className="section catalogue-intro"><div className="section-heading framed-copy"><div><p className="section-kicker">{ar?'الأدوات المناسبة لمتطلباتك':'Built around your requirements'}</p><h2><RevealText>{ar?'ابدأ بما تحتاج\nإلى قياسه.':'Start with what\nyou need to measure.'}</RevealText></h2></div><p>{ar?'من الطراز إلى التكوين، طريق واضح للوصول إلى الأداة المناسبة.':'From model to configuration, a clearer path to the instrument you need.'}</p></div><div className="category-list">{categories.map(c=><Link key={c.id} href={`/${locale}/categories/${c.id}`} className="category-row"><span className="category-icon"><MeasurementIcon category={c.id}/></span><h3>{c.name[locale]}</h3><p>{c.description[locale]}</p><span className="category-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="section selected-section"><div className="section-heading"><div><p className="section-kicker">{ar?'نظرة أقرب':'A closer look'}</p><h2><RevealText>{ar?'أدوات القياس،\nبكل تفاصيلها.':'Instruments,\nin detail.'}</RevealText></h2></div><Link className="text-link" href={`/${locale}/products`}>{t.all}<span aria-hidden="true">↗</span></Link></div><div className="featured-grid">{featured.map(p=><ProductCard key={p.id} product={p} locale={locale} demo={source==='demo'}/>)}</div></section>
 <WikaEvidence locale={locale}/><section id="approach" className="approach section"><div className="framed-copy"><p className="section-kicker">{ar?'من المتطلبات إلى عرض السعر':'From requirement to quotation'}</p><h2><RevealText>{ar?'التفاصيل أولاً.\nثم القرار.':'The details first.\nThe decision next.'}</RevealText></h2><p className="approach-description">{ar?'الطراز ليس سوى البداية. يتيح طلب عرض السعر تأكيد التكوين والتوفر والتفاصيل التجارية قبل اتخاذ القرار.':'The model is only the beginning. A quotation enquiry brings configuration, availability and commercial details into the same conversation.'}</p></div><ol className="process-list">{(ar?[['حدد أداتك','ابحث بالطراز أو تصفح حسب فئة القياس.'],['اجمع متطلباتك','أضف الأدوات والكميات إلى سلة عرض السعر.'],['أكد التفاصيل','تُراجع الملاءمة الفنية والتوفر والسعر قبل الاتفاق.']]:[['Find your instrument','Search by model or explore a measurement category.'],['Build your requirement','Collect instruments and quantities in your quote basket.'],['Confirm the details','Technical suitability, availability and pricing need confirmation.']]).map(([title,desc],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></li>)}</ol></section>
 <section className="section industries" id="industries"><div className="section-heading framed-copy"><div><p className="section-kicker">{ar?'سياق كل عملية':'The context behind every process'}</p><h2><RevealText>{ar?'تختلف القطاعات.\nوتبقى أهمية الدقة.':'Different industries.\nThe same attention to detail.'}</RevealText></h2></div></div><div className="industry-list">{industries.map(item=><Link href={`/${locale}/industries/${item.id}`} key={item.id}><span className="industry-dot"/><h3>{item[locale].title}</h3><span aria-hidden="true">↗</span></Link>)}</div><p className="industry-note">{ar?'يجب تأكيد ملاءمة الأداة لكل تطبيق بواسطة المراجع الفني.':'Instrument suitability for each application requires technical confirmation.'}</p></section><section className="closing"><p>{ar?'هل تعرف ما تبحث عنه؟':'Know what you’re looking for?'}</p><h2><RevealText>{ar?'ابدأ بالطراز.':'Start with the model.'}</RevealText></h2><Link className="button button-light" href={`/${locale}/products`}>{t.browse}<span aria-hidden="true">↗</span></Link></section></>;
}
