import Link from 'next/link';
import {notFound} from 'next/navigation';
import {loadCatalogue} from '@/lib/load-catalogue';
import {copy} from '@/content/copy';
import {isLocale} from '@/lib/catalogue';
import {Instrument} from '@/components/instrument';
import {AddToQuote} from '@/components/add-to-quote';
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}){const {products,categories,source}=await loadCatalogue();const {locale,slug}=await params;const p=products.find(p=>p.id===slug);return {title:p?`${p.model} · ${p.name[locale==='ar'?'ar':'en']}`:'Instrument'};}
export default async function Page({params}:{params:Promise<{locale:string;slug:string}>}){
 const {products,categories,source}=await loadCatalogue();const {locale,slug}=await params,p=products.find(p=>p.id===slug);if(!isLocale(locale)||!p)notFound();const t=copy[locale];
 return <div className="product-page"><p className="breadcrumb"><Link href={`/${locale}`}>{t.home}</Link> / <Link href={`/${locale}/products`}>{t.catalogue}</Link> / <bdi>{p.model}</bdi></p><div className="product-detail"><div className="detail-visual"><Instrument kind={p.category}/><p>{t.illustration}</p></div><div className="detail-copy"><Link className="section-kicker" href={`/${locale}/categories/${p.category}`}>{categories.find(c=>c.id===p.category)?.name[locale]}</Link><p className="model">{p.model}</p><h1>{p.name[locale]}</h1><p className="detail-description">{p.description[locale]}</p><p className="availability"><span/>{t.availability}</p><AddToQuote id={p.id} locale={locale}/><div className="product-assurance"><p>{locale==='en'?'Select the model. Confirm the configuration.':'اختر الطراز. وأكد التكوين.'}</p><span>{locale==='en'?'Adding to your basket does not reserve stock or place an order.':'الإضافة إلى السلة لا تحجز مخزوناً ولا تنشئ طلب شراء.'}</span></div><p className="detail-notice">{source==='cms'?(locale==='en'?'Configuration and availability require confirmation.':'يتطلب التكوين والتوفر التأكيد.') : locale==='en'?'This is a sample record, not a product offered for sale. No factory stock is represented.':'هذا سجل تجريبي وليس منتجاً معروضاً للبيع. لا يمثل مخزوناً فعلياً.'}</p></div></div><section className="technical-section"><h2>{t.technical}</h2><p>{t.pending}</p><dl><div><dt>{locale==='en'?'Model reference':'مرجع الطراز'}</dt><dd><bdi>{p.model}</bdi></dd></div><div><dt>{t.category}</dt><dd>{categories.find(c=>c.id===p.category)?.name[locale]}</dd></div><div><dt>{locale==='en'?'Source status':'حالة المصدر'}</dt><dd>{source==='demo'?t.sample:(locale==='en'?'Reviewed catalogue record':'سجل كتالوج تمت مراجعته')}</dd></div></dl></section><Link className="text-link" href={`/${locale}/products`}>{t.back}</Link></div>;
}
