'use client';
import {useLiveReport} from './use-live-report';
import {type InterestReport} from '@/lib/product-interest';
const count=(value:number)=>new Intl.NumberFormat('en').format(value);
export function ProductInterestReport({initial}:{initial:InterestReport}){
  const params=new URLSearchParams(initial.filters).toString();
  const {data:report,automatic,setAutomatic,error,loading,refresh}=useLiveReport(initial,`/api/staff/product-interest?${params}`,initial.updatedAt);
  const csv=new URLSearchParams({...report.filters,format:'csv'});
  const {filters}=initial;
  return <>
    <section className="demand-heading"><h1>Which products attract attention.</h1><p>Measured product interest, followed by actual customer requests. Catalogue CTR shows how often a visible product leads to an opening.</p><p><a href="/staff/reports">Open saved RFQ demand and requested quantities</a></p></section>
    <section aria-labelledby="interest-filters"><h2 id="interest-filters">Choose the view</h2><form method="get" action="/staff/products" className="demand-filters"><fieldset>
      <legend className="demand-sr-only">Filter product interest</legend>
      <label>From<input type="date" name="start" defaultValue={filters.start} required/></label><label>Through<input type="date" name="end" defaultValue={filters.end} required/></label>
      <label>Language<select name="locale" defaultValue={filters.locale}><option value="all">Both languages</option><option value="en">English</option><option value="ar">Arabic</option></select></label>
      <label>Device at session start<select name="device" defaultValue={filters.device}><option value="all">All devices</option><option value="mobile">Mobile width</option><option value="desktop">Desktop width</option></select></label>
      <label>Product context<select name="list" defaultValue={filters.list}><option value="all">All contexts</option><option value="catalogue">Catalogue</option><option value="category">Category</option><option value="search">Search results</option><option value="home">Homepage</option><option value="detail">Product page</option></select></label>
      <label>Sort by<select name="sort" defaultValue={filters.sort}><option value="selections">Product selections</option><option value="impressions">Visible sessions</option><option value="ctr">CTR</option><option value="views">Product page views</option><option value="basketAdds">Basket additions</option></select></label>
    </fieldset><p className="muted">Up to 93 days, inclusive, in Cairo time. All contexts deduplicates the same session across lists; context totals must not be added together.</p><div className="demand-actions"><button type="submit">Apply filters</button><a href="/staff/products">Reset filters</a></div></form></section>
    <section aria-labelledby="interest-results"><div className="demand-table-heading"><h2 id="interest-results">Product interest</h2><a className="button secondary" href={`/api/staff/product-interest?${csv}`}>Download CSV</a></div>
      <div className="interest-refresh"><button type="button" className="secondary" onClick={()=>void refresh()} disabled={loading}>{loading?'Refreshing…':'Refresh now'}</button><label><input type="checkbox" checked={automatic} onChange={event=>setAutomatic(event.target.checked)}/> Update every 30 seconds</label></div>
      <p className="muted">Last successful update: <time dateTime={report.updatedAt}>{new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'medium',timeZone:'Africa/Cairo'}).format(new Date(report.updatedAt))}</time> (Cairo). Updates pause in a hidden tab.</p>
      {error&&<p className="interest-warning" role="alert">{error} <a href="/admin/login?redirect=%2Fstaff%2Fproducts">Staff sign in</a></p>}
      {!report.enabled&&<p className="interest-warning">Collection is not active on this deployment. The report is available, but new visitor measurements will appear only after the database migration and collection setting are activated.</p>}
      {report.rows.length===0?<div className="demand-empty"><h3>No measured product activity in this view</h3><p>Measurements begin after activation and visitor consent. Try a wider date range or clear the filters. Historical traffic cannot be reconstructed.</p></div>:<div className="table-scroll" role="region" aria-label="Per-product interest" tabIndex={0}><table><caption>Each count represents distinct consenting 30-minute sessions per product, not unique people. “Selected” includes only sessions with a matching measured impression in the same context and date range.</caption><thead><tr><th scope="col">Model</th><th scope="col">Visible</th><th scope="col">Selected</th><th scope="col">CTR</th><th scope="col">Page views</th><th scope="col">Basket adds</th><th scope="col">Datasheets</th></tr></thead><tbody>{report.rows.map(row=><tr key={row.productId}><th scope="row"><a href={`/en/products/${row.productId}`}><bdi>{row.model}</bdi></a>{row.smallSample&&<span className="interest-small">Small sample</span>}</th><td className="demand-number">{count(row.impressions)}</td><td className="demand-number">{count(row.selections)}</td><td className="demand-number">{row.ctr===null?'—':`${row.ctr}%`}</td><td className="demand-number">{count(row.views)}</td><td className="demand-number">{count(row.basketAdds)}</td><td className="demand-number">{count(row.datasheets)}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="demand-definitions"><h2>What these numbers mean</h2><p><strong>CTR = selected sessions ÷ visible sessions × 100.</strong> An impression needs at least half the product card within the viewport for one continuous second while the tab is visible. Quick clicks without that impression are excluded. Page views use the visible product heading; basket and datasheet counts reflect those actions.</p><p>Fewer than 30 visible sessions is labelled a small sample. This threshold is a caution, not proof of statistical significance. Compare products with enough exposure; high CTR alone does not establish buying demand.</p><p>Only visitors who allow product analytics are measured. Staff, recognized bots and privacy signals are excluded. Browser blocking, offline requests and failed collection can reduce coverage. Device means viewport width at the start of a 30-minute session.</p><p>Use <a href="/staff/reports?cohort=verified">verified RFQ demand</a> to review requested quantities. Basket additions are not submitted requests, verified requests are not sales, and document-only quotations need manual product review. Google search CTR is a separate Search Console metric.</p></section>
  </>;
}
