import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {getPayload} from 'payload';
import config from '../src/payload.config.ts';
import {submitEnquiry} from '../src/lib/submit-enquiry.ts';
import {resendVerification} from '../src/lib/verification-outbox.ts';
import {deliverNextVerification} from '../src/lib/verification-email-worker.ts';
import {confirmVerification,tokenDigest} from '../src/lib/enquiry-verification.ts';
import {openMessage} from '../src/lib/verification-message.ts';
if(process.env.CMS_DATABASE_CHECK!=='development')throw new Error('Development database only');
const payload=await getPayload({config}),pool=payload.db.pool,keys=Array.from({length:8},()=>randomUUID());
const settings={secret:process.env.PAYLOAD_SECRET!,origin:'https://example.invalid',from:'sender@example.invalid'};
const catalogue={source:'cms' as const,categories:[],products:[]};
const input={locale:'en',contact:{name:'Outbox test',company:'Disposable test',email:'verification@example.invalid',notes:''},lines:[],manual:{model:'TEST',quantity:1,range:'0–10 bar'}};
const row=async(reference:string)=>(await pool.query('SELECT * FROM verification_emails WHERE reference=$1',[reference])).rows[0];
const token=(message:{text:string})=>message.text.split('#token=')[1];
const initial=await pool.query("SELECT id FROM verification_emails WHERE status IN ('pending','processing')");
assert.equal(initial.rowCount,0,'Requires idle development verification queue');
let calls:unknown[]=[];
const transport={send:async(message:unknown)=>{calls.push(message);return {id:'fake-receipt'};}};
try{
 const original=payload.create.bind(payload);
 payload.create=(async(options:any)=>{if(options.collection==='verification-emails')throw new Error('Injected queue failure');return original(options);}) as typeof payload.create;
 try{await assert.rejects(submitEnquiry(payload,{...input,requestKey:keys[0]},catalogue,settings));}finally{payload.create=original;}
 assert.equal((await pool.query('SELECT id FROM enquiries WHERE request_key=$1',[keys[0]])).rowCount,0,'Outbox failure rolls back enquiry');
 const demo=await submitEnquiry(payload,{...input,requestKey:keys[1]},{...catalogue,source:'demo'},settings);
 assert.equal(await row(demo.reference),undefined,'Demo never queues customer email');
 const submitted=await submitEnquiry(payload,{...input,requestKey:keys[2]},catalogue,settings);
 assert.equal((await submitEnquiry(payload,{...input,requestKey:keys[2]},catalogue,settings)).reference,submitted.reference);
 let queued=await row(submitted.reference);
 const firstMessage=openMessage(queued.sealed_message,settings.secret,queued.delivery_key),firstToken=token(firstMessage);
 assert.ok(firstToken);assert.equal(queued.sealed_message.includes(firstToken),false);
 assert.equal((await pool.query('SELECT token_hash FROM enquiry_verifications WHERE enquiry_id=$1',[queued.enquiry_id])).rows[0].token_hash,tokenDigest(firstToken));
 assert.equal((await resendVerification(payload,submitted.reference,settings)).outcome,'cooldown');
 const owner={id:1,collection:'staff' as const,role:'owner' as const};
 const visible=await payload.find({collection:'verification-emails',overrideAccess:false,user:owner,where:{reference:{equals:submitted.reference}},depth:0});
 assert.equal(visible.docs.length,1);assert.equal(visible.docs[0].sealedMessage,undefined);assert.equal(visible.docs[0].deliveryKey,undefined);
 await assert.rejects(payload.find({collection:'verification-emails',overrideAccess:false}));
 const failed=await deliverNextVerification(payload,settings.secret,{send:async(message)=>{calls.push(message);throw new Error('private failure');}});
 assert.equal(failed.outcome,'retry');
 assert.equal((await deliverNextVerification(payload,settings.secret,transport)).outcome,'empty','Backoff enforced');
 await pool.query('UPDATE verification_emails SET next_attempt_at=now() WHERE id=$1',[queued.id]);
 const outcomes=await Promise.all([deliverNextVerification(payload,settings.secret,transport),deliverNextVerification(payload,settings.secret,transport)]);
 assert.equal(outcomes.filter(x=>x.outcome==='sent').length,1);assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1],'Retry preserves complete message and key');
 queued=await row(submitted.reference);assert.equal(queued.sealed_message,null,'Erase replayable message after provider acceptance');
 await pool.query("UPDATE verification_emails SET last_issued_at=now()-interval '2 minutes' WHERE id=$1",[queued.id]);
 const resends=await Promise.all([resendVerification(payload,submitted.reference,settings),resendVerification(payload,submitted.reference,settings)]);
 assert.equal(resends.filter(x=>x.outcome==='queued').length,1);assert.equal(resends.filter(x=>x.outcome==='cooldown').length,1);
 assert.equal(await confirmVerification(payload,firstToken),null,'Resend invalidates previous link');
 queued=await row(submitted.reference);
 const replacementToken=token(openMessage(queued.sealed_message,settings.secret,queued.delivery_key));
 assert.equal((await confirmVerification(payload,replacementToken))?.mode,'customer');
 assert.equal((await deliverNextVerification(payload,settings.secret,transport)).outcome,'empty','Confirmed enquiries never start another send');
 assert.equal((await row(submitted.reference)).status,'cancelled');
 assert.equal((await resendVerification(payload,submitted.reference,settings)).outcome,'unavailable');
 const limited=await submitEnquiry(payload,{...input,requestKey:keys[3]},catalogue,settings);
 for(let count=0;count<2;count++){
  await pool.query("UPDATE verification_emails SET last_issued_at=now()-interval '2 minutes' WHERE reference=$1",[limited.reference]);
  assert.equal((await resendVerification(payload,limited.reference,settings)).outcome,'queued');
 }
 await pool.query("UPDATE verification_emails SET last_issued_at=now()-interval '2 minutes' WHERE reference=$1",[limited.reference]);
 assert.equal((await resendVerification(payload,limited.reference,settings)).outcome,'limited');
 await pool.query("UPDATE verification_emails SET issuance_window_ends_at=now()-interval '1 second' WHERE reference=$1",[limited.reference]);
 assert.equal((await resendVerification(payload,limited.reference,settings)).outcome,'queued','24-hour issuance window resets');
 await pool.query("UPDATE verification_emails SET expires_at=now()-interval '1 second' WHERE reference=$1",[limited.reference]);
 assert.equal((await deliverNextVerification(payload,settings.secret,transport)).outcome,'empty');
 assert.equal((await row(limited.reference)).status,'cancelled');
 const leased=await submitEnquiry(payload,{...input,requestKey:keys[4]},catalogue,settings);
 await pool.query("UPDATE verification_emails SET status='processing',lease_token='old',lease_expires_at=now()+interval '5 minutes',last_issued_at=now()-interval '2 minutes' WHERE reference=$1",[leased.reference]);
 assert.equal((await resendVerification(payload,leased.reference,settings)).outcome,'cooldown','Cannot replace an active send');
 await pool.query("UPDATE verification_emails SET lease_expires_at=now()-interval '1 second',attempts=5 WHERE reference=$1",[leased.reference]);
 assert.equal((await deliverNextVerification(payload,settings.secret,transport)).outcome,'empty');
 assert.equal((await row(leased.reference)).status,'failed');
 const stale=await submitEnquiry(payload,{...input,requestKey:keys[5]},catalogue,settings);
 assert.equal((await deliverNextVerification(payload,settings.secret,{send:async()=>{
  await pool.query("UPDATE verification_emails SET lease_token='replacement' WHERE reference=$1",[stale.reference]);return {id:'stale-receipt'};
 }})).outcome,'stale','Old completion cannot overwrite a replacement lease');
 await pool.query("UPDATE verification_emails SET lease_expires_at=now()-interval '1 second',attempts=5 WHERE reference=$1",[stale.reference]);
 await deliverNextVerification(payload,settings.secret,transport);
 const exhausted=await submitEnquiry(payload,{...input,requestKey:keys[6]},catalogue,settings);
 await pool.query('UPDATE verification_emails SET attempts=4 WHERE reference=$1',[exhausted.reference]);
 assert.equal((await deliverNextVerification(payload,settings.secret,{send:async()=>{throw new Error('private');}})).outcome,'failed');
 assert.equal((await row(exhausted.reference)).sealed_message,null);
 const tampered=await submitEnquiry(payload,{...input,requestKey:keys[7]},catalogue,settings);
 const previousCalls=calls.length;
 await pool.query("UPDATE verification_emails SET sealed_message='invalid',attempts=4 WHERE reference=$1",[tampered.reference]);
 assert.equal((await deliverNextVerification(payload,settings.secret,transport)).outcome,'failed');assert.equal(calls.length,previousCalls);
 console.log('Verification email checks succeeded: atomic rollback, demo exclusion, private encrypted content, stable retries, contention, rotation, single-use confirmation, cooldown/quota, expiry, leases, stale results, exhaustion and tamper rejection. Fake sender only.');
}finally{
 const records=await payload.find({collection:'enquiries',overrideAccess:true,where:{requestKey:{in:keys}},depth:0,limit:100});
 const ids=records.docs.map(x=>x.id);
 if(ids.length)for(const collection of ['verification-emails','enquiry-verifications','notifications'] as const)await payload.delete({collection,overrideAccess:true,where:{enquiry:{in:ids}}});
 await payload.delete({collection:'enquiries',overrideAccess:true,where:{requestKey:{in:keys}}});
 assert.equal(Object.keys(payload.db.sessions??{}).length,0);await payload.destroy();
}
console.log('Disposable outbox records removed.');process.exit(0);
