/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
  };
  blocks: {};
  collections: {
    staff: Staff;
    categories: Category;
    products: Product;
    skus: Skus;
    enquiries: Enquiry;
    notifications: Notification;
    'enquiry-verifications': EnquiryVerification;
    'request-limits': RequestLimit;
    'verification-emails': VerificationEmail;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    staff: StaffSelect<false> | StaffSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    skus: SkusSelect<false> | SkusSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'enquiry-verifications': EnquiryVerificationsSelect<false> | EnquiryVerificationsSelect<true>;
    'request-limits': RequestLimitsSelect<false> | RequestLimitsSelect<true>;
    'verification-emails': VerificationEmailsSelect<false> | VerificationEmailsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  role: 'owner' | 'catalogue-editor' | 'sales' | 'warehouse';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  key: string;
  name: {
    en: string;
    ar: string;
  };
  description: {
    en: string;
    ar: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  externalId: string;
  model: string;
  category: number | Category;
  name: {
    en: string;
    ar: string;
  };
  description: {
    en: string;
    ar: string;
  };
  instrumentType?:
    ('pressure-gauge' | 'pressure-transmitter' | 'pressure-switch' | 'temperature-instrument' | 'accessory') | null;
  /**
   * Choose only applications supported by reviewed manufacturer information.
   */
  applications?: ('oil-gas' | 'general-industry')[] | null;
  /**
   * Link to the actual model datasheet. Verify the document and reuse rights before publishing.
   */
  datasheetUrl?: string | null;
  sourceRef: string;
  reviewedBy?: (number | null) | Staff;
  reviewedAt?: string | null;
  rightsConfirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skus".
 */
export interface Skus {
  id: number;
  skuCode: string;
  product: number | Product;
  manufacturerPartNumber?: string | null;
  configuration:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Saved requests. Email delivery and stock reservation are not active yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  reference: string;
  requestKey: string;
  fingerprint: string;
  locale: 'en' | 'ar';
  source: 'demo' | 'cms';
  name: string;
  email: string;
  company: string;
  notes?: string | null;
  items: {
    productId: string;
    model: string;
    nameEn: string;
    nameAr: string;
    quantity: number;
    range?: string | null;
    id?: string | null;
  }[];
  verificationStatus: 'unverified' | 'test-verified' | 'verified';
  verifiedAt?: string | null;
  deliveryStatus: 'not-configured';
  status: 'new' | 'reviewing' | 'awaiting-customer' | 'quoted' | 'closed';
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sample requests never send. Delivery requires explicit sender activation. Sent means provider accepted, not confirmed inbox delivery. Failed records require review; do not reset attempts or change their creation date.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  reference: string;
  enquiry: number | Enquiry;
  deliveryKey: string;
  recipient: string;
  source: 'demo' | 'cms';
  status: 'disabled' | 'pending' | 'processing' | 'sent' | 'failed';
  attempts: number;
  nextAttemptAt?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  sentAt?: string | null;
  providerMessageId?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-verifications".
 */
export interface EnquiryVerification {
  id: number;
  enquiry: number | Enquiry;
  tokenHash: string;
  expiresAt: string;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "request-limits".
 */
export interface RequestLimit {
  id: number;
  key: string;
  hits: number;
  windowEndsAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer confirmation delivery. Sample enquiries never send. Sent means provider acceptance, not confirmed inbox delivery. Message contents are encrypted and excluded from staff API access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-emails".
 */
export interface VerificationEmail {
  id: number;
  reference: string;
  enquiry: number | Enquiry;
  deliveryKey: string;
  sealedMessage?: string | null;
  status: 'pending' | 'processing' | 'sent' | 'failed' | 'cancelled';
  attempts: number;
  nextAttemptAt?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  expiresAt: string;
  sentAt?: string | null;
  providerMessageId?: string | null;
  lastError?: string | null;
  issueCount: number;
  issuanceWindowEndsAt: string;
  lastIssuedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'skus';
        value: number | Skus;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'enquiry-verifications';
        value: number | EnquiryVerification;
      } | null)
    | ({
        relationTo: 'request-limits';
        value: number | RequestLimit;
      } | null)
    | ({
        relationTo: 'verification-emails';
        value: number | VerificationEmail;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  key?: T;
  name?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  description?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  externalId?: T;
  model?: T;
  category?: T;
  name?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  description?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  instrumentType?: T;
  applications?: T;
  datasheetUrl?: T;
  sourceRef?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  rightsConfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skus_select".
 */
export interface SkusSelect<T extends boolean = true> {
  skuCode?: T;
  product?: T;
  manufacturerPartNumber?: T;
  configuration?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  reference?: T;
  requestKey?: T;
  fingerprint?: T;
  locale?: T;
  source?: T;
  name?: T;
  email?: T;
  company?: T;
  notes?: T;
  items?:
    | T
    | {
        productId?: T;
        model?: T;
        nameEn?: T;
        nameAr?: T;
        quantity?: T;
        range?: T;
        id?: T;
      };
  verificationStatus?: T;
  verifiedAt?: T;
  deliveryStatus?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  reference?: T;
  enquiry?: T;
  deliveryKey?: T;
  recipient?: T;
  source?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  sentAt?: T;
  providerMessageId?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-verifications_select".
 */
export interface EnquiryVerificationsSelect<T extends boolean = true> {
  enquiry?: T;
  tokenHash?: T;
  expiresAt?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "request-limits_select".
 */
export interface RequestLimitsSelect<T extends boolean = true> {
  key?: T;
  hits?: T;
  windowEndsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-emails_select".
 */
export interface VerificationEmailsSelect<T extends boolean = true> {
  reference?: T;
  enquiry?: T;
  deliveryKey?: T;
  sealedMessage?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  expiresAt?: T;
  sentAt?: T;
  providerMessageId?: T;
  lastError?: T;
  issueCount?: T;
  issuanceWindowEndsAt?: T;
  lastIssuedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}